const { BOX_TYPES } = APP_SETTINGS;

export const LEVELS = [
  {
    minimumScore: 3,
    board: [
      [BOX_TYPES.RED, BOX_TYPES.BLUE, BOX_TYPES.PINK],
      [BOX_TYPES.BLUE, BOX_TYPES.PURPLE, BOX_TYPES.ORANGE],
      [BOX_TYPES.BLUE, BOX_TYPES.GREEN, BOX_TYPES.YELLOW],
    ],
    onlyColors: [BOX_TYPES.RED, BOX_TYPES.BLUE, BOX_TYPES.PURPLE],
  },
  {
    minimumScore: 6,
    board: [
      [BOX_TYPES.BLUE, BOX_TYPES.BLUE, BOX_TYPES.RED, BOX_TYPES.YELLOW],
      [BOX_TYPES.PURPLE, BOX_TYPES.BLUE, BOX_TYPES.PURPLE, BOX_TYPES.GREEN],
      [BOX_TYPES.BLUE, BOX_TYPES.RED, BOX_TYPES.PURPLE, BOX_TYPES.RED],
    ],
    onlyColors: [BOX_TYPES.RED, BOX_TYPES.BLUE, BOX_TYPES.PURPLE],
  },
];
